import type { Metadata } from "next";
import { montserrat } from "@/styles/theme/fonts";
import { PropsWithChildren } from "react";
import { Providers } from "@/components/providers/Providers";
import { GET_TOKEN } from "@/actions/token.actions";
import { redirect } from "next/navigation";
import { Sidebar } from "@/app/(application)/components/Sidebar/Sidebar";
import { SocketInit } from "@/app/(application)/components/SocketInit/SocketInit";
import { api } from "@/constants/api";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getUser() {
  const token = await GET_TOKEN();

  if (!token) return redirect("/login");

  const user = await api.get<User>("/user/profile", {
    headers: { Authorization: `Bearer ${token}` },
  });

  return { user: user.data, token };
}

export default async function RootLayout({ children }: PropsWithChildren) {
  const { token, user } = await getUser();

  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AppRouterCacheProvider>
          <Providers>
            <SocketInit token={token} user={user} />
            <Sidebar />
            {children}
          </Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
